
[tool.poetry]
name = "rna-saluki-cnn"
version = "0.1.0"
description = "Saluki plugin for biolm_utils"
authors = ["Your Name <your.email@example.com>"]
packages = [{ include = "saluki_plugin" }]


[tool.poetry.dependencies]
python = "^3.10"
mlflow = "^3.6.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.0"

[tool.poetry.group.preprocessing]
optional = true

[tool.poetry.group.preprocessing.dependencies]
gffutils = "*"
biopython = "*"
pandas = "*"
pyyaml = "*"


[tool.poetry.plugins."biolm.plugins"]
saluki = "saluki_plugin.config:get_saluki_config"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
